package com.locus.jlo.web.constant;

public enum SequenceType {
	BRANCH, NEWS, CON, HOSPITAL, SERVICE_REQUEST, INCIDENT, COMPLAINT, ACTIVITY, ASSET, CONSULTING, 
	ACTIVITY_CP, ACTIVITY_INC, ACTIVITY_SR, 
	SELFI, COMPANY, INFR, INFS, 
	KB, FAQ, GEN, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, CATEGORY5
}
